Switch
iPriMeRL/Qt-Quick-Training pull request #1
Opened 2022-06-23 14:03 UTC by iPriMeRL

The switch is a feature for alarms. Basically you have to click on it to activate/deactivate it

2022-06-24 10:15 UTC, GendoIkari commented on Digital Clock/AlarmSwitch.qml
> +        source: "/assets/switch-on-selected.svg"
Un suggerimento, potevi fare qui la selezione dei casi per avere una sola immagine:

`source: {
     if (root.disabled) return "switch-on-disabled.svg"
     if (root.off) return "switch-off-disabled.svg"
}`

2022-06-24 10:17 UTC, GendoIkari commented on Digital Clock/AlarmSwitch.qml
> +        opacity: 0
Oppure, conservando le 4 immagini:
```
opacitiy: root.disabled ? 1 : 0
```

2022-06-28 08:09 UTC, lucaotta requested changes
Ti ho lasciato solo qualche piccolo commento. Risolti quelli per me si può mergiare

2022-06-28 08:09 UTC, lucaotta commented on Digital Clock/AlarmSwitch.qml
> +        }
Puoi sostituire questo if esplicito con un operatore ternario, che a mio avviso fa meno "rumore" durante la lettura.
```suggestion
        source: root.onOrOff ? "/assets/switch-on-selected.svg" : "/assets/switch-on-disable.svg"
```

2022-06-28 08:09 UTC, lucaotta commented on Digital Clock/AlarmSwitch.qml
> +    property bool onOrOff: false
Che ne dici se questa property la chiamassi `isOn`? Mi sembra che renda lo stesso concetto e la reputo più leggibile se usi gli operatori ternari o la negazione unaria. Confronta:
```javascript
if (!onOrOff) ...
// oppure nei binding
source: onOrOff ? "img1" : "img2"
```
L'alternativa:
```javascript
if (!isOn) ...
// oppure nei binding
source: isOn ? "img1" : "img2"
```

2022-06-28 08:09 UTC, lucaotta commented on Digital Clock/AlarmSwitch.qml
> +        }
Stesso commento dell'altro

2022-06-28 08:09 UTC, lucaotta commented on Digital Clock/AlarmSwitch.qml
> +                root.color = "#313848"
Suggerimento: usa il meno possibile il codice Javascript. Come potresti riscrivere questo assegnamento a `color` (e quello successivo) in modo dichiarativo? È possibile usare dei property bindings secondo te?

2022-06-28 15:33 UTC, closed without merging